### ISSUE TITLE
chmod: cannot access '/root/output_data/*': No such file or directory

### ISSUE THREAD

**Issue by Mikor-mkr** [jacobs-robotics/docker-camodocal#2]
Hello everyone,

thanks for taking the time to check my issue here is my problem, when I run this to calibrate a camera:` ./docker_helper.sh run "intrinsic_calib -w 12 -h 11 -s 59 -i /root/input_data --camera-model pinhole -p left- --opencv -e .png"`

I get the following error as the title says:
`
chmod: cannot access '/root/output_data/*': No such file or directory`

Any idea?

**Comment by arturokkboss33** [comment]
Hello. Sorry for late reply.

I investigated and it is because the orginal Camodocal software hardcoded the path and filename for the intrinsic_calib use case. One way would be to fork their code and add an output option.
For now, I pushed a somewhat "hacky" solution. I added a command that allows you to enter the container and run the commands natively inside it. Unfortunately, then you will have to move manually the output files to the /root/output_data directory in order for them to be accessible to the host machine. See README of the latest commit at this point in time 99c3bf6 

Thanks for pointing this out
